#pragma once

enum class TraceHitType
{
    TRACE_HITTYPE_NONE = 0x0,
    TRACE_HITTYPE_ENTITY = 0x1,
    TRACE_HITTYPE_DYNENT_MODEL = 0x2,
    TRACE_HITTYPE_DYNENT_BRUSH = 0x3,
    TRACE_HITTYPE_GLASS = 0x4,
};
